### ISSUE TITLE
Loading initial data for "delivery" doesn't work.

### ISSUE THREAD

**Issue by madmath** [savoirfairelinux/sous-chef#474]
### Expected Behaviour

Loading the data works

### Actual Behaviour

```
root@16f5fa7f0056:/code/src# python3 manage.py loaddata delivery_initial_data
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 64, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 110, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 355, in check_constraints
    bad_row[1], referenced_table_name, referenced_column_name,
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'auth_permission' with primary key '94' has an invalid foreign key: auth_permission.content_type_id contains a value '32' that does not have a corresponding value in django_content_type.id.
```

### Steps to reproduce

* Start from scratch
* do all migrations, create super user, etc.
* ` python3 manage.py loaddata delivery_initial_data` fails as shown above.

@manumilou

**Comment by philippemouchel** [comment]
Just to confirm you're not alone. Same error this morning when re-installing project.
