### ISSUE TITLE
Creating an order for a client with no meal preferences raises an error

### ISSUE THREAD

**Issue by peakwinter** [savoirfairelinux/sous-chef#706]
### Expected Behaviour

When using the New Orders page in the development environment, attempting to create an order for a client that has never had a meals schedule set should not raise any errors.

### Actual Behaviour

When using the New Orders page, attempting to create an order for a client that has never had any meals schedule set raises an HTTP Error 500.

My understanding is that this would never happen in production (because creating a new client also creates a new meal schedule, even if it's empty) but it is a nuisance in development with the fixture data.

### Steps to reproduce

* Back up existing data from the development environment and flush: `python manage.py flush`
* Load sample data: `python manage.py createsuperuser` then `python manage.py loaddata sample_data`
* In Orders > New Order, attempt to create a new order for Bob Newman.

### Stacktrace

```
web_1    | Internal Server Error: /order/create/batch
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
web_1    |     return self.dispatch(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
web_1    |     return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 92, in dispatch
web_1    |     return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
web_1    |     return handler(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 185, in post
web_1    |     return self.form_invalid(form)
web_1    |   File "/code/src/order/views.py", line 194, in form_invalid
web_1    |     context = self.get_context_data(**kwargs)
web_1    |   File "/code/src/order/views.py", line 158, in get_context_data
web_1    |     meals_default_dict = dict(c.meals_schedule)
web_1    |   File "/code/src/member/models.py", line 715, in meals_schedule
web_1    |     if day not in simple_meals_schedule:
web_1    | TypeError: argument of type 'NoneType' is not iterable
web_1    | [21/Mar/2017 14:36:07] "POST /order/create/batch HTTP/1.1" 500 101993
```

**Comment by lingxiaoyang** [comment]
@peakwinter  Yes, this should not happen in production but we could lose data integrity anytime in regards to the database. That is to say, it's still necessary to fix it at the application side.
