### ISSUE TITLE
Docker web container can't connect to DB container on Windows

### ISSUE THREAD

**Issue by Jamie22** [savoirfairelinux/sous-chef#729]
I run docker-compose up from the docker quickstart terminal and get the following output:

```
$ docker-compose up
souschef_db_1 is up-to-date
souschef_web_1 is up-to-date
souschef_nginx_1 is up-to-date
Attaching to souschef_db_1, souschef_web_1, souschef_nginx_1
db_1     | Initializing database
db_1     | 2017-04-18 18:39:00 140039682103232 [Note] /usr/sbin/mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 58 ...
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: The InnoDB memory heap is disabled
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Using Linux native AIO
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Using generic crc32 instructions
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Setting file ./ibdata1 size to 12 MB
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Setting log file ./ib_logfile101 size to 48 MB
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Setting log file ./ib_logfile1 size to 48 MB
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
db_1     | 2017-04-18 18:39:01 140039682103232 [Warning] InnoDB: New log files created, LSN=45883
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Doublewrite buffer not found: creating new
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Doublewrite buffer created
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: 128 rollback segment(s) are active.
db_1     | 2017-04-18 18:39:01 140039682103232 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Foreign key constraint system tables created
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Creating tablespace and datafile system tables.
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Tablespace and datafile system tables created.
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB: Waiting for purge to start
db_1     | 2017-04-18 18:39:01 140039682103232 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 0
db_1     | 2017-04-18 18:39:01 140038906021632 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] /usr/sbin/mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 87 ...
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: The InnoDB memory heap is disabled
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Using Linux native AIO
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Using generic crc32 instructions
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Highest supported file format is Barracuda.
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: 128 rollback segment(s) are active.
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB: Waiting for purge to start
db_1     | 2017-04-18 18:39:04 139904332498880 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616799
db_1     | 2017-04-18 18:39:04 139903555831552 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] /usr/sbin/mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 116 ...
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: The InnoDB memory heap is disabled
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Compressed tables use zlib 1.2.8
web_1    | Performing system checks...
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Using Linux native AIO
web_1    |
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Using generic crc32 instructions
web_1    | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f077b102bf8>
web_1    | Traceback (most recent call last):
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Initializing buffer pool, size = 256.0M
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Completed initialization of buffer pool
web_1    |     self.connect()
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Highest supported file format is Barracuda.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: 128 rollback segment(s) are active.
web_1    |     self.connection = self.get_new_connection(conn_params)
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB: Waiting for purge to start
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
web_1    |     conn = Database.connect(**conn_params)
db_1     | 2017-04-18 18:39:07 140432426371008 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616809
web_1    |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
db_1     | 2017-04-18 18:39:08 140431652259584 [Note] InnoDB: Dumping buffer pool(s) not yet started
web_1    |     return Connection(*args, **kwargs)
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
db_1     | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
web_1    |     super(Connection, self).__init__(*args, **kwargs2)
db_1     | To do so, start the server, then issue the following commands:
web_1    | _mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
db_1     |
web_1    |
db_1     | '/usr/bin/mysqladmin' -u root password 'new-password'
web_1    | The above exception was the direct cause of the following exception:
db_1     | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
web_1    |
db_1     |
web_1    | Traceback (most recent call last):
db_1     | Alternatively you can run:
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
db_1     | '/usr/bin/mysql_secure_installation'
web_1    |     fn(*args, **kwargs)
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
db_1     | which will also give you the option of removing the test
web_1    |     self.check(display_num_errors=True)
db_1     | databases and anonymous user created by default.  This is
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
db_1     | strongly recommended for production servers.
web_1    |     include_deployment_checks=include_deployment_checks,
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
db_1     | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
web_1    |     return checks.run_checks(**kwargs)
db_1     | MySQL manual for more instructions.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
db_1     |
web_1    |     new_errors = check(app_configs=app_configs)
db_1     | Please report any problems at http://mariadb.org/jira
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
db_1     |
web_1    |     errors.extend(model.check(**kwargs))
db_1     | The latest information about MariaDB is available at http://mariadb.org/.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1266, in check
db_1     | You can find additional information about the MySQL part at:
web_1    |     errors.extend(cls._check_fields(**kwargs))
db_1     | http://dev.mysql.com
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1337, in _check_fields
db_1     | Consider joining MariaDB's strong and vibrant community:
web_1    |     errors.extend(field.check(**kwargs))
db_1     | https://mariadb.org/get-involved/
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 893, in check
db_1     |
web_1    |     errors = super(AutoField, self).check(**kwargs)
db_1     | Database initialized
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 208, in check
db_1     | MySQL init process in progress...
web_1    |     errors.extend(self._check_backend_specific_checks(**kwargs))
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 149 ...
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 311, in _check_backend_specific_checks
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Using mutexes to ref count buffer pool pages
web_1    |     return connections[db].validation.check_field(self, **kwargs)
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: The InnoDB memory heap is disabled
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/validation.py", line 41, in check_field
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
web_1    |     field_type = field.db_type(connection)
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 629, in db_type
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Compressed tables use zlib 1.2.8
web_1    |     return connection.data_types[self.get_internal_type()] % data
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Using Linux native AIO
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Using generic crc32 instructions
web_1    |     return getattr(connections[DEFAULT_DB_ALIAS], item)
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Initializing buffer pool, size = 256.0M
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Completed initialization of buffer pool
web_1    |     res = instance.__dict__[self.name] = self.func(instance)
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Highest supported file format is Barracuda.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 183, in data_types
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: 128 rollback segment(s) are active.
web_1    |     if self.features.supports_microsecond_precision:
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB: Waiting for purge to start
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616819
web_1    |     res = instance.__dict__[self.name] = self.func(instance)
db_1     | 2017-04-18 18:39:11 140574401201920 [Note] InnoDB: Dumping buffer pool(s) not yet started
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/features.py", line 54, in supports_microsecond_precision
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] Plugin 'FEEDBACK' is disabled.
web_1    |     return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
db_1     | 2017-04-18 18:39:11 140575175608256 [Warning] 'user' entry 'root@2b0c0a47bdb1' ignored in --skip-name-resolve mode.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
db_1     | 2017-04-18 18:39:11 140575175608256 [Warning] 'proxies_priv' entry '@% root@2b0c0a47bdb1' ignored in --skip-name-resolve mode.
web_1    |     res = instance.__dict__[self.name] = self.func(instance)
db_1     | 2017-04-18 18:39:11 140575175608256 [Note] mysqld: ready for connections.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 367, in mysql_version
db_1     | Version: '10.1.22-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
web_1    |     with self.temporary_connection() as cursor:
db_1     | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
web_1    |   File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
db_1     | 2017-04-18 18:39:15 140575174740736 [Warning] 'proxies_priv' entry '@% root@2b0c0a47bdb1' ignored in --skip-name-resolve mode.
web_1    |     return next(self.gen)
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 564, in temporary_connection
db_1     | 2017-04-18 18:39:15 140575174437632 [Note] mysqld: Normal shutdown
web_1    |     cursor = self.cursor()
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 231, in cursor
db_1     | 2017-04-18 18:39:15 140575174437632 [Note] Event Scheduler: Purging the queue. 0 events
web_1    |     cursor = self.make_debug_cursor(self._cursor())
db_1     | 2017-04-18 18:39:15 140574384416512 [Note] InnoDB: FTS optimize thread exiting.
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
db_1     | 2017-04-18 18:39:15 140575174437632 [Note] InnoDB: Starting shutdown...
web_1    |     self.ensure_connection()
db_1     | 2017-04-18 18:39:15 140575174437632 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
db_1     | 2017-04-18 18:39:17 140575174437632 [Note] InnoDB: Shutdown completed; log sequence number 1616829
web_1    |     self.connect()
db_1     | 2017-04-18 18:39:17 140575174437632 [Note] mysqld: Shutdown complete
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
db_1     |
web_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
db_1     | MySQL init process done. Ready for start up.
web_1    |     raise value.with_traceback(tb)
db_1     |
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] mysqld (mysqld 10.1.22-MariaDB-1~jessie) starting as process 1 ...
web_1    |     self.connect()
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Using mutexes to ref count buffer pool pages
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: The InnoDB memory heap is disabled
web_1    |     self.connection = self.get_new_connection(conn_params)
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
web_1    |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
web_1    |     conn = Database.connect(**conn_params)
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Compressed tables use zlib 1.2.8
web_1    |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Using Linux native AIO
web_1    |     return Connection(*args, **kwargs)
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Using generic crc32 instructions
web_1    |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Initializing buffer pool, size = 256.0M
web_1    |     super(Connection, self).__init__(*args, **kwargs2)
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Completed initialization of buffer pool
web_1    | django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Highest supported file format is Barracuda.
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: 128 rollback segment(s) are active.
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB: Waiting for purge to start
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1616829
db_1     | 2017-04-18 18:39:17 140464195864320 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] Plugin 'FEEDBACK' is disabled.
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] Server socket created on IP: '::'.
db_1     | 2017-04-18 18:39:17 140464971216832 [Warning] 'proxies_priv' entry '@% root@2b0c0a47bdb1' ignored in --skip-name-resolve mode.
db_1     | 2017-04-18 18:39:17 140464971216832 [Note] mysqld: ready for connections.
db_1     | Version: '10.1.22-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```
At this point it just stops without going back to the command line. When I open another docker terminal window and try to runserver I get this:

```
root@e2387a31b135:/code/src# python manage.py runserver 0.0.0.0:8080
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fac035341e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1266, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1337, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 893, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 208, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 311, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/validation.py", line 41, in check_field
    field_type = field.db_type(connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 629, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/usr/local/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 183, in data_types
    if self.features.supports_microsecond_precision:
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/features.py", line 54, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 367, in mysql_version
    with self.temporary_connection() as cursor:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 564, in temporary_connection
    cursor = self.cursor()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

erortiz tried to help me solve this in the IRC chat room but was stumped because I'm still able to connect to the database manually from inside the web container.

**Comment by lingxiaoyang** [comment]
I confirm this issue using Docker Toolbox on a Windows 10 VM (hosted on Ubuntu 16.04):

![image](https://cloud.githubusercontent.com/assets/8630726/25541848/43a013da-2c1e-11e7-82fe-ea19275cd942.png)

**Comment by lingxiaoyang** [comment]
The reason is found! 

@Jamie22 Remove these two lines: https://github.com/savoirfairelinux/sous-chef/blob/7278d965ad17cfd39372451a6484dd6e90e0e894/docker-compose.yml#L9-L10 and try `docker-compose up` again.

This absolute path mapping syntax was from Docker 2 but still supported by Docker 3 on Linux. On Windows, however, version '2' is not well supported. You can compare the difference from the Docker docs:
https://docs.docker.com/compose/compose-file/#volume-configuration-reference
https://docs.docker.com/compose/compose-file/compose-file-v2/#volumes-volumedriver

Please let me know if this works for you. By the way, I was testing with Docker for Windows instead of Docker Toolbox (the one written in INSTALL.md) for better performance in the Windows VM. There might be a difference.

For this issue, here are what we really need to fix:
1. Update docker-compose.yml from version 2 to version 3 (for a better platform support).
2. Update docs to encourage the use of Docker for Windows/Mac instead of old solution Docker Toolbox.

**Comment by lingxiaoyang** [comment]
Developer note (to be added somewhere as "testing in Windows"):

**Testing with Docker for Windows** (recommended):

Use Win10 as Docker for Windows requires Hyper-V. A VM image is officially provided by [Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). Select the correct version and **VirtualBox** platform and download.

Important: for the host software, I had to use a 30-day trial VMWare Workstation instead of open-source VirtualBox on Ubuntu 16.04 because VMWare had a much better nested virtualization support. In fact, Docker for Windows refused to install when I was using VirtualBox.

Recommended settings: RAM 6GB with 2 CPU Cores. I checked "Virtualize Intel VT-x/EPT or AMD-V/RVI" and selected preferred mode as "Intel VT-x or AMD-V". Perhaps there could be a better choice but I'm not testing further.

**Testing with Docker Toolbox**:

Only if you need to test on Win7/8. When testing with Win10, you have to disable Hyper-V.

**Comment by erozqba** [comment]
@lingxiaoyang great job!

**Comment by Jamie22** [comment]
Thanks lingxiaoyang. I got it working with Docker for Windows.

**Comment by lingxiaoyang** [comment]
@Jamie22  Cool!
