### ISSUE TITLE
Extra npm installs

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#756]
[INSTALL.md](https://github.com/savoirfairelinux/sous-chef/blob/dev/INSTALL.md) says I should be able to

```
docker-compose up -d
docker-compose exec web sh -c "cd tools/gulp && npm install --unsafe-perm && gulp"
```

but when I do this from a fresh install, I get `no such file or directory, '/code/tools/gulp/node_modules/node-sass/vendor'`:

```
root@sous-chef-test:/home/sfl/sous-chef# docker-compose exec web bash
WARNING: Some networks were defined but are not used by any service: frontend
root@cfc1f03106e5:/code# cd tools/gulp/
root@cfc1f03106e5:/code/tools/gulp# gulp
[07:13:39] Local gulp not found in /code/tools/gulp
[07:13:39] Try running: npm install gulp
root@cfc1f03106e5:/code/tools/gulp# npm install --unsafe-perm
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /code/tools/gulp/node_modules/node-sass
> node scripts/install.js


root@cfc1f03106e5:/code/tools/gulp# gulp
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/code/tools/gulp/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/code/tools/gulp/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/code/tools/gulp/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/code/tools/gulp/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/code/tools/gulp/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/code/tools/gulp/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/code/tools/gulp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

which is because `tools/gulp/node_modules/....` is missing
(and this file is missing whether or not I pass `--unsafe-perm`)

Investigating, you can see what while the `node-sass` module was apparently installed, it is missing pieces:

```
root@cfc1f03106e5:/code/tools/gulp# ls node_modules/node-sass/
CHANGELOG.md  LICENSE  README.md  bin  binding.gyp  lib  node_modules  package.json  scripts  src  test
root@cfc1f03106e5:/code/tools/gulp# ls node_modules/node-sass/vendor
ls: cannot access node_modules/node-sass/vendor: No such file or directory
```

Manually installing fixes it (?!):

```
root@cfc1f03106e5:/code/tools/gulp# npm install node-sass

> node-sass@4.5.3 install /code/tools/gulp/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node
Download complete  ] - :
Binary saved to /code/tools/gulp/node_modules/node-sass/vendor/linux-x64-48/binding.node
Caching binary to /root/.npm/node-sass/4.5.3/linux-x64-48_binding.node

> node-sass@4.5.3 postinstall /code/tools/gulp/node_modules/node-sass
> node scripts/build.js

Binary found at /code/tools/gulp/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
sous-chef-skel@1.0.0 /code/tools/gulp
└─┬ gulp-sass@3.1.0
  └── node-sass@4.5.3 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
root@cfc1f03106e5:/code/tools/gulp# ls node_modules/node-sass/vendor
linux-x64-48
```

But then there's another error

```
root@cfc1f03106e5:/code/tools/gulp# gulp
[07:23:09] Using gulpfile /code/tools/gulp/gulpfile.js
[07:23:09] Starting 'default'...
[07:23:09] Starting 'styles'...
[07:23:09] Starting 'scripts-multidatespicker'...
[07:23:09] Starting 'scripts-leaflet'...
[07:23:09] Starting 'scripts'...
[07:23:09] Starting 'images'...
[07:23:09] Finished 'default' after 146 ms
Unhandled rejection Error: spawn /code/tools/gulp/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[07:23:11] multidatespicker.js went from 22.51 kB to 10.60 kB and is 52.92% smaller.
[07:23:11] Finished 'scripts-multidatespicker' after 1.76 s
[07:23:14] leaflet.js went from 271.81 kB to 156.62 kB and is 42.38% smaller.
[07:23:14] Finished 'scripts-leaflet' after 4.45 s
[07:23:14] main.min.css went from 23.55 kB to 18.85 kB and is 19.95% smaller.
[07:23:14] Finished 'styles' after 4.73 s
[07:23:15] sous-chef.js went from 92.63 kB to 34.76 kB and is 62.47% smaller.
[07:23:15] Finished 'scripts' after 5.47 s
```

which has the same half-installed symptom:

```
root@cfc1f03106e5:/code/tools/gulp# ls node_modules/optipng-bin/
cli.js  index.js  lib  license  package.json  readme.md
```

In all, I found several packages that didn't fully install (?!) when called with `npm install`, and I needed to add these additional commands to make it work:
```
npm install node-sass   # or `rebuild` works too; tip from https://github.com/sass/node-sass/issues/1387#issuecomment-185451183
npm install optipng-bin
npm install gifsicle
npm install jpegtran-bin
```

@lingxiaoyang told me via email earlier today that he had issues with these same packages too. I suspect that since `docker-compose.override.yml` says `volume: .:/code/`, Ling solved this once and then never had to again, since the node dependencies survive docker rebuilds. But I think it needs a real solution, because this means the code in the repo is unusable as-is.

Ideally the root cause would be found but at the least, the documentation needs to change to add these extra commands.

### Steps to reproduce

```
git clone https://github.com/savoirfairelinux/sous-chef/
$ cd sous-chef
$ docker-compose build
$ docker-compose up -d
$ docker-compose exec web bash
# cd tools/gulp
# npm install --unsafe-perm
# gulp
```

**Comment by kousu** [comment]
The Dockerfile currently says
```
curl -cL https://deb.nodesource.com/setup_6.x | bash
```

I think this choice is showing its age. I experimented with changing that line to say "8.x" and found that it completely solved this:

```
sfl@sous-chef-test$ docker-compose up --build -d
[ lots of waiting ]
root@sous-chef-test:/home/sfl/sous-chef# docker-compose exec web bash
root@66b230c37669:/code# ls
CONTRIBUTING.md  INSTALL.md  README.adoc             docker-compose.prod.yml  docs                mock_clients.csv  mock_orders.csv         requirements.txt  tools
Dockerfile       LICENSE     docker-compose.dev.yml  docker-compose.yml       mock_addresses.csv  mock_meals.csv    mock_relationships.csv  src
root@66b230c37669:/code# cd tools/gulp/
root@66b230c37669:/code/tools/gulp# gulp
[07:33:12] Local gulp not found in /code/tools/gulp
[07:33:12] Try running: npm install gulp
root@66b230c37669:/code/tools/gulp# npm install --unsafe-perm
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use '
npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /code/tools/gulp/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /code/tools/gulp/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> fsevents@1.1.2 install /code/tools/gulp/node_modules/fsevents
> node install


> optipng-bin@3.1.4 postinstall /code/tools/gulp/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /code/tools/gulp/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@3.0.4 postinstall /code/tools/gulp/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> node-sass@4.5.3 postinstall /code/tools/gulp/node_modules/node-sass
> node scripts/build.js

Binary found at /code/tools/gulp/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
added 826 packages in 68.256s
root@66b230c37669:/code/tools/gulp# gulp
[07:35:16] Using gulpfile /code/tools/gulp/gulpfile.js
[07:35:16] Starting 'default'...
[07:35:16] Starting 'styles'...
[07:35:16] Starting 'scripts-multidatespicker'...
[07:35:16] Starting 'scripts-leaflet'...
[07:35:16] Starting 'scripts'...
[07:35:16] Starting 'images'...
[07:35:16] Finished 'default' after 84 ms
[07:35:18] multidatespicker.js went from 22.51 kB to 10.60 kB and is 52.92% smaller.
[07:35:18] Finished 'scripts-multidatespicker' after 1.94 s
[07:35:22] leaflet.js went from 271.81 kB to 156.62 kB and is 42.38% smaller.
[07:35:22] main.min.css went from 23.55 kB to 18.85 kB and is 19.95% smaller.
[07:35:22] Finished 'styles' after 6.26 s
[07:35:22] Finished 'scripts-leaflet' after 6.21 s
[07:35:24] sous-chef.js went from 92.63 kB to 34.76 kB and is 62.47% smaller.
[07:35:24] Finished 'scripts' after 7.63 s
[07:35:33] Finished 'images' after 16 s

```

The packages in npm must not all be backwards compatible, but also not be marked as such. Thanks npm! You're super trustworthy and reliable.

Please consider upgrading the version of Node you're using. I doubt I can reliably deploy to our test server until you do. Will that break anything on your end?

**Comment by kousu** [comment]
I wonder why the Travis-CI build didn't catch this. Does Travis-CI not do a clean build? After much confusion I realized that `docker-compose.override.yml` which is invoked implicitly was loop-mounting `./` into the container, which meant that `tools/gulp/node_modules` were survivng builds, and perhaps since our js depends don't change that rapidly you would only need one working build once for it to keep working for a long time.

**Comment by kousu** [comment]
Answering my own question: the Travis build [doesn't use docker](https://api.travis-ci.org/jobs/246100654/log.txt?deansi=true). It also is on an ancient Ubuntu (12.04).
